host = "localhost"             #host
user = "user"              #User name
password = "password123"       #Password for postgre user (if needed, works without it)
db = "testDB"              #Database Name
main_table = "blacklist_veritawall2"       #This will be changed
groupe_table = "groupe_int2"  #This will be changed
path_to_db = "../databases/DB"  #File which containes the database in csv format for instance
perf_file = "../performances"   #Precise where to save the file where the performances of the algorithm are stored
suricata_table = "suricata_table2"
suricata_blacklist_file = "../suricata_rules/blacklist_veritawall_suricata2"
path_to_shalla_list = "../databases/BL"
DF_path = '../veritawall-filtering'
groupe_database = groupe_table
